import { store } from '../core/Store';
import { Icons } from '../utils/Icons';

export const Sidebar = {
  render() {
    const slides = store.slides;
    const activeSlide = store.activeSlide;

    const listItems = slides.map((slide, index) => {
      const isActive = activeSlide && slide.id === activeSlide.id;
      return `
        <div class="slide-thumbnail ${isActive ? 'active' : ''}" data-id="${slide.id}" draggable="true">
          <div class="thumbnail-header">
            <span class="slide-num">${index + 1}</span>
            <div class="slide-actions">
              <button class="action-btn move-up" data-id="${slide.id}" title="Move Up">${Icons.moveUp}</button>
              <button class="action-btn move-down" data-id="${slide.id}" title="Move Down">${Icons.moveDown}</button>
              <button class="action-btn delete-btn" data-id="${slide.id}" title="Delete">${Icons.delete}</button>
            </div>
          </div>
          <div class="thumbnail-preview">
            <!-- Simple preview: Title text or Layout icon -->
            <small>${slide.content.title || 'Untitled'}</small>
            <br>
            <span class="layout-badge">${slide.layout}</span>
          </div>
        </div>
      `;
    }).join('');

    return `
      <div class="sidebar">
        ${listItems}
      </div>
    `;
  },

  attachEvents(container) {
    let draggedId = null;

    // Selection
    container.querySelectorAll('.slide-thumbnail').forEach(el => {
      // 1. Click Selection
      el.addEventListener('click', (e) => {
        if (e.target.closest('.action-btn')) return;
        store.setActiveSlide(el.dataset.id);
      });

      // 2. Drag Start
      el.addEventListener('dragstart', (e) => {
         draggedId = el.dataset.id;
         e.dataTransfer.effectAllowed = 'move';
         el.classList.add('dragging');
         // Ghost image auto-generated by browser from element
      });

      // 3. Drag End
      el.addEventListener('dragend', (e) => {
         el.classList.remove('dragging');
         container.querySelectorAll('.slide-thumbnail').forEach(t => t.classList.remove('drag-over'));
         draggedId = null;
      });

      // 4. Drag Over (Allow Drop)
      el.addEventListener('dragover', (e) => {
         e.preventDefault(); // Necessary to allow dropping
         e.dataTransfer.dropEffect = 'move';
         el.classList.add('drag-over');
      });

      // 5. Drag Leave
      el.addEventListener('dragleave', (e) => {
         el.classList.remove('drag-over');
      });

      // 6. Drop
      el.addEventListener('drop', (e) => {
         e.preventDefault();
         el.classList.remove('drag-over');
         if (!draggedId || draggedId === el.dataset.id) return;

         // Find target index
         const allSlides = Array.from(container.querySelectorAll('.slide-thumbnail'));
         const targetIndex = allSlides.findIndex(node => node.dataset.id === el.dataset.id);
         
         // Reorder
         store.reorderSlide(draggedId, targetIndex);
      });
    });

    // Action Buttons
    container.querySelectorAll('.delete-btn').forEach(btn => {
      btn.addEventListener('click', (e) => store.deleteSlide(btn.dataset.id));
    });
    
    // Legacy Move Buttons (Optional, keep for accessibility?)
    container.querySelectorAll('.move-up').forEach(btn => {
      btn.addEventListener('click', () => store.moveSlide(btn.dataset.id, 'up'));
    });
    container.querySelectorAll('.move-down').forEach(btn => {
      btn.addEventListener('click', () => store.moveSlide(btn.dataset.id, 'down'));
    });
  }
};
